### ISSUE TITLE
build fails on ubuntu

### ISSUE THREAD

**Issue by t-sin** [mimium-org/mimium#60]
Building dev branch fails on Ubuntu. Here is a part of build logs:

```
[ 97%] Building CXX object src/CMakeFiles/mimium_exe.dir/main.cpp.o
[100%] Linking CXX executable mimium
/usr/bin/ld: -lPolly が見つかりません
/usr/bin/ld: -lPollyISL が見つかりません
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/mimium_exe.dir/build.make:108: src/mimium] エラー 1
make[1]: *** [CMakeFiles/Makefile2:379: src/CMakeFiles/mimium_exe.dir/all] エラー 2
make: *** [Makefile:152: all] エラー 2
```

## To reproduce

```
$ git clone https://github.com/mimium-org/mimium
$ cd mimium
$ cmake -B build
# fails this command
$ cmake --build ./build/ -j
```

## Expected behavior

Building process successfully finishes.

## Environment

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

$ uname -a
Linux timberwolf 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ apt show llvm
Package: llvm
Version: 1:10.0-50~exp1
Priority: optional
Section: universe/devel
Source: llvm-defaults (0.50~exp1)
Origin: Ubuntu
...
```

**Comment by tomoyanonymous** [comment]
I remember that `llvm` package in apt does not contain polly while it required by `llvm-config --libs`. I don't know why but that's why llvm is installed via homebrew in our Github Actions.

https://github.com/mimium-org/mimium/blob/0bcde248e066e4799fed4ad415c3d3a7c18cf771/.github/workflows/build_and_test.yml#L78

Maybe installing with `sudo apt-get install llvm-toolchain` or installing with the automatic installation script in https://apt.llvm.org/ solves, I will make test PR soon.

**Comment by tomoyanonymous** [comment]
https://mimium.org/en/docs/developers-guide/setup-development-environments/　updated docs

**Comment by t-sin** [comment]
Thanks! I tried with official automatic installation script, it succeeded. And, it's a nice documentation.

I'll close this issue.
